### ISSUE TITLE
Unimplemented functions

### ISSUE THREAD

**Issue by keikoro** [agonzalezro/python-opensubtitles#13]
Hi there, are you still planning to implement the API calls that are currently not implemented? I was wondering about that because yours seems to be the most popular wrapper (going by PyPI and GitHub stars) but it looks like development stalled two years ago.

**Comment by SkullTech** [comment]
Yeah, I think we need to start active development on this again. I'll try to participate too.

**Comment by agonzalezro** [comment]
Hi folks,

there is no plan to implement the functions that are not already implemented but I would be more than happy to accept PRs for those.

If you are willing to help in that my plan would be to add come kind of CI and mock the tests, they are currently searching for a local file (it was "good" at the time, but not anymore).

Thanks for your patience, I did this project time ago but I am not using it anymore.

**Comment by kerstin** [comment]
Heya, I cannot commit to helping a certain amount of time (... or lines of code :P) but actually do need the download function so could _try_ to contribute? I'm new/newish to both CI + tests, but based on how I've seen other projects do it, they seem to make a lot of sense.

**Comment by agonzalezro** [comment]
Give it a try @kerstin :) We can help you in case you need.

**Comment by kerstin** [comment]
Hey, I'm about to submit something (yay!).
I noticed one other (unrelated) thing, will open a separate issue for that.
