### ISSUE TITLE
User Agent

### ISSUE THREAD

**Issue by kerstin** [agonzalezro/python-opensubtitles#14]
If I read OpenSubtitles' API info/[dev rules](http://trac.opensubtitles.org/projects/opensubtitles/wiki/DevReadFirst) correctly, no public-facing app or code is supposed to contain their special user agent for testing. However, `settings.py` does (and there are no instructions on removing those settings and replacing them with one's own, either).

I'd suggest removing these values altogether and including some info in the README on how to register for a developer account and how to modify the settings with one's own dev data.

I'd volunteer to do make these changes and send a PR.

**Comment by kerstin** [comment]
Oh, only just saw that this was actually already discussed in #11 around a year ago. Well maybe it's time it also got implemented.

**Comment by agonzalezro** [comment]
Done in #21
