### ISSUE TITLE
Add a way to change the user agent

### ISSUE THREAD

**Issue by agonzalezro** [agonzalezro/python-opensubtitles#20]
Previously discussed here: https://github.com/agonzalezro/python-opensubtitles/issues/14 and https://github.com/agonzalezro/python-opensubtitles/issues/11

The agent is set here: https://github.com/agonzalezro/python-opensubtitles/blob/master/pythonopensubtitles/settings.py#L3 but there isn't an easy way to override settings.

**Comment by kerstin** [comment]
I was thinking maybe via environment variables / a `settings.conf` file for which a template gets provided (`settings.conf.template` or similar), which the user must fill in with their own variables and put it in the dir from which they are running their script before first use.

Similar to how one would save settings for web apps (Django) or scripts that are run on a PaaS like Heroku (where you add the env vars directly, but might also have them saved in a non-version-controlled file on your HD for running the script locally)

**Comment by agonzalezro** [comment]
@kerstin that could be a good idea if `python-opensubtitles` was a CLI, but being a library I am not sure that (only) offering a way to set the UserAgent with the env var is enough.

I think `UserAgent` should be part of the constructor and optional to don't break backwards compatibility. Adding the env var as well is ok.

Thanks for yous thoughts!

**Comment by kerstin** [comment]
Btw. they changed the user agent for testing again. (;

**Comment by agonzalezro** [comment]
@kerstin willing to do it? 😄
