### ISSUE TITLE
Return raw decoded_data from download_subtitles method

### ISSUE THREAD

**Issue by iezepov** [agonzalezro/python-opensubtitles#31]
It would be really nice to have an option to return `decoded_data` from the `download_subtitles` method. I have some processing after the download, so now I have to write to a temp directory and read afterward.

I'm not sure what would be the right way to implement it when multiple ids are provided. I'm thinking about a list of `decoded_data` for corresponding ids. Or maybe to `yield` the data (more pythonic I would say but in that case the function behaviour will change a lot depending on the proposed optional argument, so a list is probably better).

Either way, I can implement it, need only a decision about the return type.

**Comment by agonzalezro** [comment]
Hi @iezepov, thanks for the feedback.

That's actually a good idea but could you provide a prototype of how the API would look like? We usually return `true/false` and with this change we would break this behaviour. Any thought on it?

**Comment by iezepov** [comment]
Could you clarify about `true/false`? I'm a little confused because it seems that `download_subtitles` returns Dict or None.

If that's the case then we can keep the return type to be `Dict[str->str]` (currently it is `id->fpath`) and cahnge it to `id->decoded_data` right here: https://github.com/agonzalezro/python-opensubtitles/blob/master/pythonopensubtitles/opensubtitles.py#L194

**Comment by iezepov** [comment]
@agonzalezro I drafetd an implementation, could you take a look in the PR and let me know what you think?

**Comment by agonzalezro** [comment]
Sorry about the "true/false" comment, it doesn't apply here.

I commented on the PR, I like it as it is. Either we return the path or the data sounds good 👍
