### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by ceo-domido** [agonzalezro/python-opensubtitles#39]
When I try to download some no-english subs there is an utf8 codec error. In example:

> from pythonopensubtitles.opensubtitles import OpenSubtitles
> ost = OpenSubtitles()
> token = ost.login('xxxx', 'xxxx')
> data = ost.search_subtitles([{'sublanguageid': 'rus', 'query': 'Two and half men', 'season': 1, 'episode': 1}])
> import pandas
> pd = pandas.DataFrame(data)
> sb = ost.download_subtitles([pd.IDSubtitleFile[0]])

> 'utf8' codec can't decode byte 0xc4 in position 34: invalid continuation byte
> UnicodeEncodeErrorTraceback (most recent call last)
>      14 pd = pandas.DataFrame(data)
>      15 pd
> ---> 16 sb = ost.download_subtitles([pd.IDSubtitleFile[0]])
>      17 sb
> pyannote-audio\src\python-opensubtitles\pythonopensubtitles\opensubtitles.pyc in download_subtitles(self, ids, override_filenames, output_directory, override_directories, extension, return_decoded_data)
>     207                 try:
>     208                     with open(fpath, 'w') as f:
> --> 209                         f.write(decoded_data)
>     210                     successful[subfile_id] = fpath
>     211                 except IOError as e:

**Comment by ceo-domido** [comment]
The same situation when param return_decoded_data = True established.
> sb = ost.download_subtitles([pd.IDSubtitleFile[0]], return_decoded_data=True)

But in case of trying to download second found file, everything is OK:

> sb = ost.download_subtitles([pd.IDSubtitleFile[1]], return_decoded_data=True)

**Comment by Ousret** [comment]
I've proposed a PR that could fix this. #38 Try it.

**Comment by agonzalezro** [comment]
Yes please, @ceo-domido try @Ousret PR and if your problem gets fixed (it should) it will be a good test for the current open PR.

@Ousret in the meantime maybe you could do the same? You have the details of the subtitle that @ceo-domido is trying to download.

Thanks for filling the issue and thanks @Ousret for the PR.

**Comment by agonzalezro** [comment]
Please, check the latest released version to see if this issue was fixed: https://pypi.org/manage/project/python-opensubtitles/releases/
