### ISSUE TITLE
Default user agent is invalid

### ISSUE THREAD

**Issue by DiGMi** [agonzalezro/python-opensubtitles#4]
Opensubtitles changed the default user agent, thus the one that you are currently using is invalid.
Please change that to: OSTestUserAgent
Thanks.

**Comment by agonzalezro** [comment]
Hi @DiGMi,

Thanks for taking your time creating the issue. I am not using this library anymore, so perhaps you could explain the problema a little bit more?

I would expect that in some point they will force a proper user agent, but is it enough if I change it to that value? Are they returnin non-200 if we don't change it?

**Comment by shyoatmeal** [comment]
Currently it returns 415 (Disabled user agent) . Changing user agent to 'OSTestUserAgent' is enough to make it work.

**Comment by agonzalezro** [comment]
Please, take a look to my proposed change.

Thanks.
