### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by SmartManoj** [agonzalezro/python-opensubtitles#42]
Write login credentials into a file
Add to context menu 
override filename by default

```
from pythonopensubtitles.opensubtitles import OpenSubtitles
from pythonopensubtitles.utils import File

ost = OpenSubtitles() 
ost.login()
import glob
path=r'C:\q\ST\ST s2'
for i in glob.glob(path+'\*.mkv'):
	try:
		f = File(i)
		data = ost.search_subtitles([{'sublanguageid': 'all', 'moviehash': f.get_hash(), 'moviebytesize': f.size}])
		id_subtitle_file = data[0].get('IDSubtitleFile')
		name=i.split('\\')[-1].rsplit('.',1)[0]
		ost.download_subtitles([id_subtitle_file],override_filenames={id_subtitle_file: f'{name}.srt'}, output_directory='', extension='srt')
	except Exception as e:
		print(data[0])
	
```

**Comment by agonzalezro** [comment]
Hi @SmartManoj thanks for the feature requests, but could you help me understand them a little bit better?

1. Login credentials from file.

You could easily do that reading the file by yourself (yaml, json, whatever) and call `login(username, password)`. If you do that in the library, where do you get the file from? What's the format? etc.

2. Context menu

What do you mean here?

3. Override by default

Why do you think that's better than the current behaviour?

Thanks!

**Comment by SmartManoj** [comment]
1. In user directory as json
2. Windows Context menu
3. So we didn't change the filename

**Comment by agonzalezro** [comment]
I am sorry, but I don't think that your feature request is general enough. You can already do that with the current state of the library by implementing the bits that are "missing" by yourself.

Thanks anyway for your feedback!
