### ISSUE TITLE
`base64.decodestring(s)` is deprecated

### ISSUE THREAD

**Issue by MrCirdo** [agonzalezro/python-opensubtitles#47]
Hi,

This function `base64.decodestring(s)` is deprecated since version 3.1 of python and it was removed since version 3.9.9 of python (according to the documentation). So the library is not compatible with latest version of python.

**Comment by agonzalezro** [comment]
Thanks for reporting @MrCirdo!

I have seen that you fixed it in your fork, could you make it backward compatible and make a PR 🙏🏽

**Comment by MrCirdo** [comment]
Your welcome. I need to test now the backward compatibility and I will make a PR

**Comment by MrCirdo** [comment]
I forgot to close the issue.
