### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by bluegeekgh** [agonzalezro/python-opensubtitles#6]
Can you please add Python 3 support?

**Comment by agonzalezro** [comment]
What problems do you have running this with py3? I almost didn't update the library since 2012.

Let me know the errors that you are getting and if it's something small perhaps I could take a look. If you know how to solve them I am happy to accept a PR.

Thanks!

**Comment by bluegeekgh** [comment]
Thanks for the feedback. I've finally created a more basic script on my own.
