### ISSUE TITLE
NameError: global name 'size' is not defined (pythonopensubtitles/utils.py)

### ISSUE THREAD

**Issue by dmcelectrico** [agonzalezro/python-opensubtitles#7]
Running the test on your README I got this error while creating the File object given a path and filename: it can't find the size function.

Python 2.7 running on Debian 7 for armhf.

Trace:
`>>> f = File(path.join("/home/foo/","bar.mkv"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_opensubtitles-0.1dev_r0-py2.7.egg/pythonopensubtitles/utils.py", line 23, in __init__
    self.size = size(os.path.getsize(path))
NameError: global name 'size' is not defined`

**Comment by creepypenguin** [comment]
It should be str(os.path.getsize(path)) instead of size(os.path.getsize(path))...I think.

**Comment by dmcelectrico** [comment]
@creepypenguin Yup, that fixed the thing, thanks. Let's wait for @agonzalezro to read this and fix it himself.

**Comment by agonzalezro** [comment]
Thanks for the comments. I've fixed it in that small commit.

I am pretty surprised that my doctest even being pretty poor/bad didn't catch this.

I would be really happy to accept some nice unitesting PR for this package :D
